[[Pango]]
arch = "x86_64"
git-tree-sha1 = "9f81349923c6a3f2e00e258fc11c96d7b4c47fcb"
os = "macos"

    [[Pango.download]]
    sha256 = "5bbcd1653ac23ca5c5b94219f26ecb4e63275040ebd9b61ddcf434b28edd7f01"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.x86_64-apple-darwin14.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "44aca0247a86d16fd8e7a7848a828467d430fbad"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "829dba09892daedf09670107f71536e92b4b751e5f07d741844330e24d29f0f4"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "c51596d038de2768c17f5a1b07a4b0037747e2d2"
os = "freebsd"

    [[Pango.download]]
    sha256 = "881d03b9cd8510ca168bcc89307682c10c229834ad57d4a1a6aa54037b55b957"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "c618b144e3b9f9beb7de17f04a15d478df0692e5"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "89889703118222b3734c8cab8291bf03fcc27ef1abebc26e196f637d59172875"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "dca565600f5d03b90fbf5b9488885221fd0915bc"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "b898c3e25dc361904114db73dcc949f88543704b6a446cce93544bbd99e1623a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "935a0a1e7fb0523900c40d4fc8753cfcac801864"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "280c98792fcfe5ec4ca125678edd836d8c85cdde8aa968814f004fec96395ce2"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "a8293380ed3a87fce5ce2d6fb006cb52446cdaee"
os = "windows"

    [[Pango.download]]
    sha256 = "c822ead422d5894cefca5077f87fe8d36ae8a6d51afd17ea66ef87d29cc13db4"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.x86_64-w64-mingw32.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "c53e21b81b243d982e4efbb5a95e18cb71d15666"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "cab6a356deed788033c559dbbf164474d74f7a70b5c5e3163412a5c17a5122ca"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "59744339da1d8daf4441a34c084d57458e73cdaa"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "955b8ba03bc0f92d33299eb31ae8a3fef6ae27fc234e0a33774df504d98761ce"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.arm-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "96c5454ecbfc661cedc015abcb7baf13851f7cb6"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "f8b06bbe4b39ebba7d173b7e381369a4fda74de2fd5504db3abf9c1eb9ecd447"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.i686-linux-musl.tar.gz"
[[Pango]]
arch = "armv7l"
git-tree-sha1 = "48d1b21a773d3f1559bd511ea6eb0ee463634835"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "9cc7d74d35bce16b48b0ebb0577ad923425820a4d560d84c3961d514d02b9ff3"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.arm-linux-musleabihf.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "bbbadb7804a01b1fd24d411d4803ec94948c7855"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "6544697d06bf6b6f4b94b74663ca595d8a5116a3bdf5c03f739ced7170795491"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "5d609be223edf93384330f401ca88c09c5fb0a92"
os = "windows"

    [[Pango.download]]
    sha256 = "99330932dc3fa7b61a1362c0ecf73f4bd6975c157523f9c1e792f16f05a8db8e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.42.4+5/Pango.v1.42.4.i686-w64-mingw32.tar.gz"
